### ISSUE TITLE
The dependency MailKit 1.2.12 in project ... does not support framework DNXCore,Version=v5.0.

### ISSUE THREAD

**Issue by eino-makitalo** [jstedfast/MimeKit#174]
I try to add with nuget this package to aspnetcore50 project (which should be run in Linux, Mac and Windows) but I got this error message. I'm not Nuget-expert. Is this easy to fix?  

The dependency MailKit 1.2.12 in project ... does not support framework DNXCore,Version=v5.0.

**Comment by jstedfast** [comment]
Correct. It does not support DNXCore. If you'll submit a patch to add that project type, I'll happily accept it.

**Comment by eino-makitalo** [comment]
Ok. I try to learn nuget little bit :-)

**Comment by jstedfast** [comment]
FWIW, I've now implemented dnxcore50 support, available in the 1.3.0-beta's on nuget.

**Comment by harit222** [comment]
I have added following dependencies in my project.json. I am still getting same error.

"MimeKit": "1.2.24",
"MailKit": "1.4.1"

**Comment by jstedfast** [comment]
If you want to use MailKit 1.4.1, you'll need MimeKit 1.4.1

**Comment by harit222** [comment]
I have used both as 1.4.1. Now both dependencies are not getting detected in DNX Core 5.0. 

![image](https://cloud.githubusercontent.com/assets/11464610/17262558/05193970-5591-11e6-9f6f-16f55df9f637.png)

**Comment by jstedfast** [comment]
DNX Core 5.0 doesn't exist anymore. You need to use NETStandard or NetCoreApp
