### ISSUE TITLE
DKIM relaxed body canonicalization 

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#190]
DKIM relaxed body canonicalization must "Ignore all whitespace at the end of lines. Implementations MUST NOT remove the CRLF at the end of the line.". This doesn't work anymore since commit https://github.com/jstedfast/MimeKit/commit/71abff2a33c5f7c156d7b443cd770829022cdbdc

Body test case:

test[CR][LF]
[SP][CR][LF]
test[CR][LF]

This must be canonicalized to:
test[CR][LF]
[CR][LF]
test[CR][LF]

**Comment by jstedfast** [comment]
This should be fixed now

**Comment by jstedfast** [comment]
I've released MimeKit 1.2.16 to NuGet with a fix for this.

**Comment by breedbekkikker** [comment]
Thanks! Unfortunately, in some cases the body hash is still not correct. By adding an extra condition it seems to work.

Old code:
```c#
                if (*inptr == (byte)'\r' && (inptr + 1) < inend && *(inptr + 1) == (byte)'\n')
```

New code:

```c#
                if (*inptr == (byte)'\r' && (inptr + 1) == inend)
                {
                    if (!IsEmptyLine)
                    {
                        *outptr++ = *inptr;
                        lwsp = false;
                        count++;
                    }
                }
                else if (*inptr == (byte)'\r' && (inptr + 1) < inend && *(inptr + 1) == (byte)'\n')
```

**Comment by jstedfast** [comment]
is your message body ending with a \r?

**Comment by jstedfast** [comment]
never mind, this can happen if the \r\n is split across buffer boundaries.

**Comment by jstedfast** [comment]
This should now be fixed in git master.

**Comment by breedbekkikker** [comment]
Thanks, the fix in git master works!

**Comment by jstedfast** [comment]
ok, I'll probably try to make another release this weekend then.

**Comment by jstedfast** [comment]
I've published 1.3.0-beta (I had to publish a beta because I've added dnxcore50 support which requires beta packages), so you can either install that nuget or a "hidden" MimeKit 1.2.17.2 nuget which is the same thing, but contains an incomplete list of dnxcore50 dependencies to get around needing to mark it as a beta.

**Comment by jstedfast** [comment]
I just published a non-hidden 1.2.17.3 nuget with this fix so you don't have to tell VS to allow pre-release nugets.
